### ISSUE TITLE
provisional status

### ISSUE THREAD

**Issue by psalaets** [psalaets/viilo#12]
You are on provisional status until you've played 5 games. While on provisional your stats are tracked but you're ranked as if your elo is 0.

**Comment by cbleslie** [comment]
I like this.

**Comment by psalaets** [comment]
Is 5 good? or should it be higher.

**Comment by cbleslie** [comment]
Yeah 5 is good for now. This could be a config file thing.

**Comment by psalaets** [comment]
@cbleslie This is in

Players now have a `provisional` property which is a boolean.

It defaults to true and is only checked after a game. So your existing players need to be in a game (or be deleted) for the provisional flag to be set right.
